version: "3.7"
services:

  db:
    image: postgres:12.4
    environment:
        POSTGRES_DB: ${DB_NAME}
        TZ: ${OS_TIMEZONE}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
        interval: 10s
        timeout: 10s
        retries: 5
    networks:
      - db_network

  phpadmin:
      image: dockage/phppgadmin
      container_name: phpadmin
      depends_on: 
        - db
      environment: 
        PHP_PG_ADMIN_SERVER_HOST: db
        PHP_PG_ADMIN_SERVER_PORT: ${DB_PORT}
      ports:
        - ${PHPADMIN_PORT}:80
      networks:
        - db_network

  django:
    build: ./backend-django/
    command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --socket :8000 --wsgi-file config/wsgi.py"
    environment: 
        DB_HOST: db
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    stdin_open: true
    ports:
      - 8000:8000
    depends_on:
      - phpadmin
    networks:
      - db_network

networks:
  db_network:
    driver: bridge